services:
  - type: web
    name: foodiehub
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    envVars:
      - key: MYSQLHOST
        value: sql12.freesqldatabase.com
      - key: MYSQLPORT
        value: "3306"
      - key: MYSQLDATABASE
        value: sql12832249
      - key: MYSQLUSER
        value: sql12832249
      - key: MYSQLPASSWORD
        value: FiqNekIwsB
