services:
  - type: web
    name: foodiehub
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    envVars:
      - key: PGHOST
        value: db.flqkcfuehagmbeuaydjx.supabase.co
      - key: PGPORT
        value: "5432"
      - key: PGDATABASE
        value: postgres
      - key: PGUSER
        value: postgres
      - key: PGPASSWORD
        value: Praveen@2005*1%
